#!/bin/sh
echo "Husky STARTED!"
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"   # preventive script for yarn on Win with Git Bash

yarn prettier-check
yarn lint
#TODO: remove after fixing axios.create of axios-module-mocking @ `dice-api-mixin.spec.js` remove start cors-server below check
#yarn cors-server
yarn test:unit-win
echo "!!! Git pre-commit check with Husky SUCCEEDED !!! :)"
