#!/bin/sh
echo "Husky STARTED!"
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"   # preventive script for yarn on Win with Git Bash

yarn prettier-check
yarn lint
#yarn jest
echo "!!! Husky SUCCEEDED !!! :)"
